name: Clang Static Analysis

on:
  push:
  pull_request:
  schedule:
    - cron: '45 3 * * SUN'

permissions: {}

jobs:
  run:
    name: "Clang Static Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          php-version: 8.4
          tools: composer, phpize

      - name: Checkout
        # We use v1 due to https://github.com/actions/checkout/issues/334
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false

      - name: Install clang-tools and libmaxminddb
        run: sudo apt update && sudo apt-get install clang-tools libmaxminddb-dev

      - name: Build extension
        run: |
              export CFLAGS="-L$HOME/libmaxminddb/lib"
              export CPPFLAGS="-I$HOME/libmaxminddb/include"
              cd ext
              phpize
              scan-build --status-bugs ./configure --with-maxminddb --enable-maxminddb-debug
              make clean
              scan-build --status-bugs make
