name: PHP Lints

on:
  push:
  pull_request:
  schedule:
    - cron: '45 3 * * SUN'

permissions: {}

jobs:
  run:
    runs-on: ubuntu-latest
    name: "PHP Lints"
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          php-version: 8.3

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Validate composer.json
        run: composer validate

      - name: Lint with php-cs-fixer
        run: vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

      - name: Lint with phpcs
        run: vendor/bin/phpcs --standard=.phpcs-ruleset.xml src/

      - name: Lint with phpstan
        run: vendor/bin/phpstan analyze
